# This is a basic workflow to help you get started with Actions
name: Deploy To VPS

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    # Comment
    steps:
      - run: | 
          cd ~/edugami-ar
          git pull origin main
          git status
          npm install
          npm run build
      # - run: 
      # - name: executing remote ssh commands using password
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     port: ${{ secrets.PORT }}
      #     script: |
      #       cd ~/my-site
      #       cd ~/my-site
      #       git pull origin main
      #       git status
      #       npm install --only=prod
      #       npm run build
      #       pm2 restart my-site-svelte